<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IND-PF0SNN2F-LT" ignored="0" name="NoonAssignment" tests="5" failures="1" timestamp="2020-09-26T20:29:01 IST" time="14.716" errors="0">
  <testcase name="validateSuccess" time="7.31" classname="org.noon.ValidateTests"/>
  <testcase name="validateError" time="1.392" classname="org.noon.ValidateTests"/>
  <testcase name="trxnHistorySuccess" time="1.548" classname="org.noon.TrxnHistoryTests"/>
  <testcase name="trxnHistoryError" time="1.497" classname="org.noon.TrxnHistoryTests"/>
  <testcase name="trxnHistoryErrorStatus404Test" time="1.619" classname="org.noon.TrxnHistoryTests">
    <failure type="java.lang.AssertionError" message="expected [Non message available] but found [No message available]">
      <![CDATA[java.lang.AssertionError: expected [Non message available] but found [No message available]
at org.noon.TrxnHistoryTests.trxnHistoryErrorStatus404Test(TrxnHistoryTests.java:77)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- trxnHistoryErrorStatus404Test -->
</testsuite> <!-- NoonAssignment -->
